### ISSUE TITLE
flint version

### ISSUE THREAD

**Issue by zteitler** [Macaulay2/homebrew-tap#102]
After `brew install Macaulay2/tap/m2` I get
```
dyld: Library not loaded: /usr/local/opt/flint/lib/libflint-15.dylib
  Referenced from: /usr/local/bin/M2-binary
  Reason: image not found
/usr/local/bin/m2: line 2: 46496 Abort trap: 6           DYLD_LIBRARY_PATH=`dirname "$0"`/../lib/Macaulay2/lib:$DYLD_LIBRARY_PATH `dirname "$0"`/M2-binary "$@"
```
Here's the output of `brew config`:
```
HOMEBREW_VERSION: 3.2.5-13-g89b8619
ORIGIN: https://github.com/Homebrew/brew
HEAD: 89b8619153ce7f523fcf4d1bb5fa4b3a375c22a4
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e245b3ea77930d2b658841b1614aec1c67c2c8d2
Core tap last commit: 10 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.UalsTyJl3J/org.macosforge.xquartz:0
HOMEBREW_EDITOR: bbedit -w
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.32.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5.1-x86_64
CLT: 12.5.0.22.9
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
```
Here's the output of `otool -L /usr/local/Cellar/macaulay2/1.18_1/bin/M2-binary | grep -i 'flint'`:
```
/usr/local/opt/flint/lib/libflint-15.dylib (compatibility version 15.0.0, current version 15.0.1)
```
Here's the output of `ls /usr/local/opt/flint/lib`:
```
libflint-16.dylib	libflint.a		libflint.dylib		libflint.dylib.16
```
Well, it's not too mysterious that it can't locate `libflint-15.dylib` because it doesn't exist, only `libflint-16`. It looks like a new version of FLINT was released about 5 days ago, <https://flintlib.org/news.html>. I tried installing a couple of earlier versions with `brew install flint@2.7.1` and `...@2.7.0`, but they didn't work (brew said those formulas weren't available).

**Comment by zteitler** [comment]
Well, that was on one of my computers. My other computer has an apparently isomorphic issue but with `gdbm` instead of `flint`: installed is a higher version of `libgdbm` than what macaulay2 is looking for. Is there something I as a user can do about these library version things?

**Comment by mahrud** [comment]
I'll rebuilt the bottle in https://github.com/Macaulay2/homebrew-tap/pull/99. If all goes well, try upgrading with `brew upgrade M2` sometime tomorrow.

**Comment by mahrud** [comment]
I guess that was mostly to resolve the flint issues. Are you still having an issue with gdbm?

**Comment by zteitler** [comment]
I'm no longer having the issue with gdbm. I did a bunch of crazy removing and reinstalling things, and I'm assuming that most of it was unnecessary, but I don't know which steps were the ones that actually made a difference. Anyway, no issue right now. Thanks for your quick response!
