### ISSUE TITLE
Csdp, clang, unknown type name inline

### ISSUE THREAD

**Issue by nobuki-takayama** [Macaulay2/homebrew-tap#103]
Hi, I tried to install M2 by 
```
 brew install Macaulay2/tap/M2
```
on M1-Mac.  However, it failed to compile Csdp.  The clang does not recognize the keyword "inline"; I guess that it needs an option to understand the c99 specification.
Many thanks in advance for advices.

* Here is the output.
```
brew install csdp
==> Downloading https://raw.githubusercontent.com/Macaulay2/M2/1f99f71a1308318679412de7f20e9
Already downloaded: /Users/nobuki/Library/Caches/Homebrew/downloads/3502d46bdfc627a4d2dd452c2bf7e15efbbf546591d07240043326fe5f64df8e--patch-6.2.0
==> Downloading https://github.com/coin-or/Csdp/archive/releases/6.2.0.tar.gz
Already downloaded: /Users/nobuki/Library/Caches/Homebrew/downloads/49d31940eb27a9babe8061a83fed6d3b764e7d86091ebbd31a2ce4b559baa31c--Csdp-releases-6.2.0.tar.gz
==> Installing csdp from macaulay2/tap
==> Patching
==> Applying patch-6.2.0
patching file Makefile
patching file example/Makefile
patching file lib/user_exit.c
patching file solver/Makefile
patching file theta/Makefile
patching file theta/rand_graph.c
==> make CC=clang ${OpenMP_C_FLAGS} ${CFLAGS} LDLIBS=${OpenMP_C_LDLIBS} LIBS=-L../lib -lsdp 
Last 15 lines from /Users/nobuki/Library/Logs/Homebrew/csdp/01.make:
clang -Xpreprocessor -fopenmp -I/opt/homebrew/opt/libomp/include -ansi -Wall -DUSEOPENMP -DSETNUMTHREADS -DUSESIGTERM -DUSEGETTIME -I../include -ansi -Wall -DUSEOPENMP -DSETNUMTHREADS -DUSESIGTERM -DUSEGETTIME -I../include   -c -o sdp.o sdp.c
clang -Xpreprocessor -fopenmp -I/opt/homebrew/opt/libomp/include -ansi -Wall -DUSEOPENMP -DSETNUMTHREADS -DUSESIGTERM -DUSEGETTIME -I../include -ansi -Wall -DUSEOPENMP -DSETNUMTHREADS -DUSESIGTERM -DUSEGETTIME -I../include   -c -o op_o.o op_o.c
clang -Xpreprocessor -fopenmp -I/opt/homebrew/opt/libomp/include -ansi -Wall -DUSEOPENMP -DSETNUMTHREADS -DUSESIGTERM -DUSEGETTIME -I../include -ansi -Wall -DUSEOPENMP -DSETNUMTHREADS -DUSESIGTERM -DUSEGETTIME -I../include   -c -o psd_feas.o psd_feas.c
clang -Xpreprocessor -fopenmp -I/opt/homebrew/opt/libomp/include -ansi -Wall -DUSEOPENMP -DSETNUMTHREADS -DUSESIGTERM -DUSEGETTIME -I../include -ansi -Wall -DUSEOPENMP -DSETNUMTHREADS -DUSESIGTERM -DUSEGETTIME -I../include   -c -o op_a.o op_a.c
clang -Xpreprocessor -fopenmp -I/opt/homebrew/opt/libomp/include -ansi -Wall -DUSEOPENMP -DSETNUMTHREADS -DUSESIGTERM -DUSEGETTIME -I../include -ansi -Wall -DUSEOPENMP -DSETNUMTHREADS -DUSESIGTERM -DUSEGETTIME -I../include   -c -o op_at.o op_at.c
clang -Xpreprocessor -fopenmp -I/opt/homebrew/opt/libomp/include -ansi -Wall -DUSEOPENMP -DSETNUMTHREADS -DUSESIGTERM -DUSEGETTIME -I../include -ansi -Wall -DUSEOPENMP -DSETNUMTHREADS -DUSESIGTERM -DUSEGETTIME -I../include   -c -o Fnorm.o Fnorm.c
clang -Xpreprocessor -fopenmp -I/opt/homebrew/opt/libomp/include -ansi -Wall -DUSEOPENMP -DSETNUMTHREADS -DUSESIGTERM -DUSEGETTIME -I../include -ansi -Wall -DUSEOPENMP -DSETNUMTHREADS -DUSESIGTERM -DUSEGETTIME -I../include   -c -o calc_pobj.o calc_pobj.c
In file included from op_o.c:15:
/opt/homebrew/opt/libomp/include/omp.h:484:12: error: unknown type name 'inline'
    static inline int omp_is_initial_device(void) { return 1; }
           ^
1 error generated.
make[1]: *** [op_o.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
```

* The "brew config" is as follows.
```
bash-3.2$ brew config
HOMEBREW_VERSION: 3.2.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: 09b7ab2c1de3ab32f385aac922b2cd644fdd7c79
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 33afcbb22f54ca27729844dbc2dd9054c43e24ce
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.cIyf8vwb3j/org.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6-arm64
CLT: 13.0.0.0.1.1630607135
Xcode: 13.0
XQuartz: 2.8.1 => /opt/X11
Rosetta 2: false
```

**Comment by mahrud** [comment]
Did you try the solution in https://github.com/Macaulay2/homebrew-tap/issues/92#issuecomment-867150098?

**Comment by mahrud** [comment]
Which package requires `libomp`, by the way? Like, if you just do
```
brew uninstall --ignore-dependencies libomp
```
and try to build csdp, what fails?

**Comment by mahrud** [comment]
Oh you said you already tried that, never mind.

**Comment by mahrud** [comment]
I don't have access to an M1 system. It would help if someone tried to build [csdp](https://github.com/coin-or/Csdp) from source on an M1 system and tell us which `configure` flags worked.

**Comment by mahrud** [comment]
Thanks @nobuki-takayama! If removing `-ansi` is all it takes then it's an easy fix. I just made #104 and will merge it once it passes the tests. Can you give it another try in a few minutes?

**Comment by nobuki-takayama** [comment]
Thanks @mahrud !  The change is already in the main branch and the building of the dependent systems are all fine! But, as it is already reported in #105, the procedure stops at 
<pre> cmake --build M2/BUILD/build-brew --target install-packages
</pre>
with several warnings of missing nodes of documents.
<pre>
-------  snip
-- warning: missing node: (prune,Complex) cited by isFree(Complex)
 -- warning: 58 warning(s) occurred in documentation for package Complexes
ninja: build stopped: subcommand failed.
</pre>
Is it a new issue?

**Comment by nobuki-takayama** [comment]
[04.cmake.log](https://github.com/Macaulay2/homebrew-tap/files/7358569/04.cmake.log)

The csdp is fine.  I attach the ~/Library/Logs/Homebrew/macaulay2/04.cmake to check the details of the failure.

**Comment by nobuki-takayama** [comment]
It seems to be a different issue. Then, I will close this issue. Many thanks!

**Comment by mahrud** [comment]
Yes, those are precisely the examples that depend on gfan! See #100. If you could help compile gfan on M1 and troubleshoot why it crashes even on the most simple examples that would be very helpful!

**Comment by youngsuKim-CSUSB** [comment]
This afternoon I got it working. My issue was related to setting up the TBB library correctly. One package installation (the last one) failed, but everything else went ok. 

I don't seem to have an issue with gfan. Mine is the iMac 24 inch.

**Comment by MichaelABurr** [comment]
@mahrud I found this issue and got around it by adding -std=gnu17 (or any other gnu standard) to the clang compiler flags (I directly compiled the files which had this issue and didn't add it to the full configure).

**Comment by mahrud** [comment]
Thanks! I'm not sure if I added a flag but I believe csdp is now bottled for brew on M1, isn't it? Meaning people don't need to compile it.
