### ISSUE TITLE
TOPCOM resource not found

### ISSUE THREAD

**Issue by David-GW** [Macaulay2/homebrew-tap#110]
The resource located at http://www.rambau.wm.uni-bayreuth.de/Software/TOPCOM-0.17.8.tar.gz no longer appears to exist, causing the installation of the "topcom" dependency to fail.

**Comment by David-GW** [comment]
Replacing the above URL with http://www.wm.uni-bayreuth.de/de/team/rambau_joerg/TOPCOM-Downloads/TOPCOM-0_17_8.tgz in the topcom.rb file in the Macaulay2 tap Formula folder seems to allow the package to be installed.

**Comment by mahrud** [comment]
Great! Do you mind making a PR to fix the download link and the website link?

**Comment by David-GW** [comment]
No problem, submitted now
