### ISSUE TITLE
Fix for the M2 tap using macOS Monterey on Apple Silicon  

### ISSUE THREAD

**Issue by jose-a-sa** [Macaulay2/homebrew-tap#123]
Hi,

I spend a few days trying to compile Macaulay2 using CMake on Apple Silicon and found a setup that (almost) builds the project perfectly on macOS 12.0.1 Monterey:

1. Install all the dependencies, including the ones on the M2/submodules using brew (now available on Apple Silicon)
2. Set the _ccache_ directory to a writable path, by overriding the CCACHE_DIR environment var, because the compiler will not have permissions to use the default path on the latest versions of macOS.
3. Use "BUILD_TESTING=OFF", which also sets "IgnoreExampleErrors=true", to bypass failures in the 2 of the internal packages installed, "ReflexivePolytopesDB" and "CohomCalg". ~I believe these errors are also due to file access.~
4. Use the default Clang compiler, not the Homebrew-provided GCC compiler (do not set CC, CXX, CMAKE_C_COMPILER, CMAKE_CXX_COMPILER)

The modified formula for Homebrew that compiles on Apple Silicon (slight modification):
![image](https://user-images.githubusercontent.com/13206784/145682961-abfd4b2c-7e48-415c-a342-9c9a30974c3e.png)

I hope this was helpful.

Best wishes, Jose

**Comment by jose-a-sa** [comment]
PS: if not using Homebrew this script also works
```
# Update Homebrew and its packages
brew update && brew upgrade
# Dependencies for building M2
deps="bison cmake ninja pkg-config bdw-gc boost eigen factory fflas-ffpack flint frobby gdbm givaro gmp libatomic_ops mpfi mpfr mpsolve ntl readline tbb@2020_u3 cohomcalg csdp fourtitwo gfan libomp lrs nauty normaliz topcom googletest mathic mathicgb memtailor mpir"
brew install $(echo $deps)
# Path for the dependencies binaries and libraries on Homebrew folder
deps=$(echo $deps | tr ' ' ';')
paths=$HOMEBREW_PREFIX/opt/${deps//;/;$HOMEBREW_PREFIX/opt/}
# Clone source code
git clone https://github.com/Macaulay2/M2.git
# Create folder to be used by 'ccache'
mkdir -p M2/M2/BUILD/build/ccache/tmp
# CMake configure (this installs on /usr/local)
cmake -GNinja -S M2/M2 -B M2/M2/BUILD/build -DBUILD_TESTING=OFF -DBUILD_NATIVE=OFF -DCMAKE_PREFIX_PATH=$paths -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local
# CMake build (redefining CCACHE_DIR env var)
CCACHE_DIR=$(pwd)/M2/M2/BUILD/build/ccache cmake --build M2/M2/BUILD/build --target build-libraries build-programs
CCACHE_DIR=$(pwd)/M2/M2/BUILD/build/ccache cmake --build M2/M2/BUILD/build --target M2-core M2-emacs
CCACHE_DIR=$(pwd)/M2/M2/BUILD/build/ccache cmake --build M2/M2/BUILD/build --target install-Macaulay2Doc
CCACHE_DIR=$(pwd)/M2/M2/BUILD/build/ccache cmake --build M2/M2/BUILD/build --target install-packages
# CMake install
sudo cmake --install M2/M2/BUILD/build
```

**Comment by mahrud** [comment]
> * Use "BUILD_TESTING=OFF", which also sets "IgnoreExampleErrors=true", to bypass failures in the 2 of the internal packages installed, "ReflexivePolytopesDB" and "CohomCalg". I believe these errors are also due to file access.

My guess would have been gfan (see https://github.com/Macaulay2/homebrew-tap/issues/100). Could you confirm whether or not `brew test gfan` passes on your system?

**Comment by jose-a-sa** [comment]
My gfan passes all the tests:
```
brew test gfan
==> Testing macaulay2/tap/gfan
==> /opt/homebrew/Cellar/gfan/0.6.2_9/bin/gfan _version
==> /opt/homebrew/Cellar/gfan/0.6.2_9/bin/gfan _overintegers --groebnerFan
==> /opt/homebrew/Cellar/gfan/0.6.2_9/bin/gfan _tropicalfunction
==> /opt/homebrew/Cellar/gfan/0.6.2_9/bin/gfan _secondaryfan
```

By running `echo "Q[x,y]\n{x^2-y^2,2*x}" | gfan _overintegers --groebnerFan` I obtained:

```
_application fan
_version 2.2
_type SymmetricFan

AMBIENT_DIM
2

DIM
2

LINEALITY_DIM
1

RAYS
-1 1	# 0
1 -1	# 1

N_RAYS
2

LINEALITY_SPACE
1 1

ORTH_LINEALITY_SPACE
1 -1

F_VECTOR
1 2

SIMPLICIAL
1

PURE
1

CONES
{}	# Dimension 1
{0}	# Dimension 2
{1}

MAXIMAL_CONES
{0}	# Dimension 2
{1}
```

I believe much of this code is written using old C/C++ standards that have been deprecated or even removed due to security concerns, thus the errors in file accessing, etc.
I am in the process of building locally M2 again, especially the 'install-packages' target, to see where the problems lie. I will find the error files related to the two packages and post them here.

Best, Jose

**Comment by mahrud** [comment]
I'm somewhat unsure what you're trying to fix then. As far as I'm aware only gfan fails on some M1 systems. If that works, then I'm not sure what is wrong.

**Comment by jose-a-sa** [comment]
Sorry, I was not entirely clear.

The homebrew-tap formula from this repo, I was getting an immediate error because of `tbb` missing a deprecated method. The reason for that is that I have both `tbb` and  `tbb@2020_u3` installed, and because of line
```
args << "-DTBB_ROOT_DIR=#{Formula["tbb"].prefix}"
```
it was setting the incorrect TBB_ROOT_DIR.

Secondly, even after changing `Formula["tbb"].prefix` -> `Formula["tbb@2020_u3"].prefix`,  I was failing to build _install-packages_ target due to `ccache` issues. So I also included
```
# Ccache fix: place files by setting CCACHE_DIR to a tmp folder (absolute path) with write permissions
current_path = "#{buildpath}"
system "mkdir", "-p", "#{current_path}/#{build_path}/ccache/tmp"
ENV["CCACHE_DIR"] = "#{current_path}/#{build_path}/ccache"
```
inside the `if OS.mac? ... end` block.

I hope that was clear.

PS: After a few checks, I discovered that this smaller modification to the formula is better than my first comment and also fixes the errors in the M2 packages "ReflexivePolytopesDB" and "CohomCalg".

**Comment by mahrud** [comment]
Did you get an error from ccache? The build path is a fresh build path every time, so I don't see how setting the ccache directory helps.

**Comment by mahrud** [comment]
I corrected the incorrect tbb name in c097b2d0cca124fc7d84ee543864f72ac354a409.

**Comment by mahrud** [comment]
If you do get errors when building M2 using brew, give this a try first:
```bash
brew install macaulay2/tap/M2 --HEAD
brew install macaulay2-common
```
If that doesn't work either, please provide the error.

I'm not going to read through the picture you attached and type it in myself, but you're welcome to make a pull request with your suggested changes.

**Comment by jose-a-sa** [comment]
Works perfectly now, also just using `brew install M2` works

**Comment by mahrud** [comment]
Great! I'll close this for now, then, but feel free to open it again if you run into ccache issues again!
