### ISSUE TITLE
Failed to download resource "factory"

### ISSUE THREAD

**Issue by icecube-bit** [Macaulay2/homebrew-tap#128]
Here is the error message I get after trying to install M2 on macOS 12.1 Monterey (M1) using homebrew: 
Error: macaulay2: Failed to download resource "factory"
Download failed: https://service.mathematik.uni-kl.de/ftp/pub/Math/Factory/factory-4.2.1.tar.gz 
Can you help me with this? Thanks.

**Comment by mahrud** [comment]
Weird! I think your best bet is to contact the people at Singular (e.g. via https://github.com/Singular/Singular/issues) that the tarfile is giving a 403 Forbidden error. If that doesn't work we can come up with an alternative solution here.

**Comment by icecube-bit** [comment]
Thanks Mahrud. I will contact people at Singular first.

Best,
Ela

**Comment by mahrud** [comment]
This seems to be fixed. Thanks for contacting them!
