### ISSUE TITLE
brew unable to download factory-4.2.1?

### ISSUE THREAD

**Issue by astaal** [Macaulay2/homebrew-tap#134]
Hi, I've been running native M2 on an M1 macbook for the past year (thanks Mahrud!).  Yesterday I ran some `brew` commands while trying to get a `jar` file working, which somehow led to a broken M2.  Trying a fresh re-install didn't work.  Now running only `brew upgrade` I see:

> ==> Upgrading 1 outdated package:
macaulay2/tap/factory 4.2.0 -> 4.2.1_1
==> Downloading https://service.mathematik.uni-kl.de/ftp/pub/Math/Factory/factory-4.2.1.tar.gz
curl: (28) Failed to connect to service.mathematik.uni-kl.de port 443 after 75011 ms: Operation timed out
Warning: Problem : timeout. Will retry in 1 seconds. 3 retries left.
curl: (28) Failed to connect to service.mathematik.uni-kl.de port 443 after 75003 ms: Operation timed out
Warning: Problem : timeout. Will retry in 2 seconds. 2 retries left.
curl: (28) Failed to connect to service.mathematik.uni-kl.de port 443 after 75004 ms: Operation timed out
Warning: Problem : timeout. Will retry in 4 seconds. 1 retries left.
curl: (28) Failed to connect to service.mathematik.uni-kl.de port 443 after 75004 ms: Operation timed out
>
>Error: factory: Failed to download resource "factory"
Download failed: https://service.mathematik.uni-kl.de/ftp/pub/Math/Factory/factory-4.2.1.tar.gz

Checking the U of Kaiserslautern math dept website, I see their IT systems are blocked and the Singular website it down (is it just me?).  Is there a workaround to get brew to finish the upgrade?

**Comment by slel** [comment]
It is not just you. This also blocks the upgrade
of the Singular Homebrew package at

- https://github.com/Homebrew/homebrew-core/pull/96180

Maybe @hannes14 can liaise with the IT services
at Uni Kaiserslautern about reenabling access
to these math software resources hosted there?

**Comment by Bckempa** [comment]
To build this I had to `brew edit` the factory recipe to use the `http://macaulay2.com/Downloads/OtherSourceCode` URL that is used by [the M2 build scripts](https://github.com/Macaulay2/M2/blob/f6a9c375e170e2abf3c9e6e740912c753f534a96/M2/libraries/factory/Makefile.in)  since the resource is not available at uni-kl.de

**Comment by astaal** [comment]
That worked for me, thanks @Bckempa !

**Comment by slel** [comment]
The download url has changed. See #136.

**Comment by mahrud** [comment]
Thank you, @Bckempa and @slel!
