### ISSUE TITLE
Host error?

### ISSUE THREAD

**Issue by edconrad** [Macaulay2/homebrew-tap#135]
I am having issues just installing this on my mac device. 
I think that maybe a host is down and it's not installing a library correctly. Below is a log of the downloads it started, and then the error.  I followed the directions on the brew install, and I don't know how to fix this. 

If I reinstall without cleaning on top of this folder, it'll download more files but eventually give me a child dependency error. 

==> Downloading https://service.mathematik.uni-kl.de/ftp/pub/Math/Factory/factory-4.2
==> Downloading from https://www.mathematik.uni-kl.de/
######################################################################## 100.0%
Error: Is a directory @ rb_file_s_rename - (/Users/joshuaandrewrice/Library/Caches/Homebrew/downloads/ecd5c13be47e5c767cafe7bde587f29ee2f8ebe1e8db5df1b6f17babac3035bc--/.incomplete, /Users/joshuaandrewrice/Library/Caches/Homebrew/downloads/ecd5c13be47e5c767cafe7bde587f29ee2f8ebe1e8db5df1b6f17babac3035bc--/)

**Comment by mahrud** [comment]
I think this is the same as #134. Could you try the solution suggested there and let me know if it works?
