### ISSUE TITLE
Failed to download resource "gfan" for Apply M1

### ISSUE THREAD

**Issue by yuriever** [Macaulay2/homebrew-tap#158]
Hi! I tried to install Macaulay2 by `brew install Macaulay2/tap/M2` and the download always gets stuck at `gfan` with the following error:

```
Error: gfan: Failed to download resource "gfan"
Download failed: https://github.com/Macaulay2/homebrew-tap/releases/download/gfan-0.6.2_10/gfan-0.6.2_10.arm64_monterey.bottle.tar.gz
```

It seems that `brew install Macaulay2/tap/M2` or `brew install macaulay2/tap/gfan` tries to download `gfan-0.6.2_10.arm64_monterey.bottle.tar.gz` but at [the release page](https://github.com/Macaulay2/homebrew-tap/releases/tag/gfan-0.6.2_10) the corresponding version of [gfan-0.6.2_9.arm64_monterey.bottle.tar.gz](https://github.com/Macaulay2/homebrew-tap/releases/download/gfan-0.6.2_10/gfan-0.6.2_9.arm64_monterey.bottle.tar.gz) doesn't match. Is there a workaround for this problem?

**Comment by mahrud** [comment]
Yes, I was in the process of rebuilding it to fix a compiler issue for Monterey. Could you help us with rebottling gfan for M1? Here are the steps:
```m2
brew uninstall --ignore-dependencies gfan
brew install --build-bottle gfan
brew bottle --no-rebuild gfan
```
Then upload the bottle somewhere and I'll update the formula. This would be greatly appreciated! If you are willing, there are a few other packages that could similarly use someone's help on M1!

**Comment by mahrud** [comment]
The other packages that need new M1 bottles: `cddlib@0.94m, topcom, frobby, macaulay2`

**Comment by yuriever** [comment]
[cddlib@0.94m--0.94m_1.arm64_monterey.bottle.tar.gz](https://github.com/Macaulay2/homebrew-tap/files/9997339/cddlib%400.94m--0.94m_1.arm64_monterey.bottle.tar.gz)
[frobby--0.9.5_4.arm64_monterey.bottle.tar.gz](https://github.com/Macaulay2/homebrew-tap/files/9997340/frobby--0.9.5_4.arm64_monterey.bottle.tar.gz)
[gfan--0.6.2_10.arm64_monterey.bottle.tar.gz](https://github.com/Macaulay2/homebrew-tap/files/9997342/gfan--0.6.2_10.arm64_monterey.bottle.tar.gz)
[topcom--0.17.8_5.arm64_monterey.bottle.tar.gz](https://github.com/Macaulay2/homebrew-tap/files/9997343/topcom--0.17.8_5.arm64_monterey.bottle.tar.gz)

The last one `macaulay2` takes time to build. I'll upload it later.

**Comment by yuriever** [comment]
The file size is a bit larger. I upload [here](https://github.com/yuriever/github-issue/tree/main/Macaulay2:homebrew-tap:issues:158)

**Comment by mahrud** [comment]
Thank you very much! All are uploaded, you should be able to run `brew install M2` now and hopefully everything should build from bottles.
