### ISSUE TITLE
installed file says it's version 1.19

### ISSUE THREAD

**Issue by eisenbud** [Macaulay2/homebrew-tap#168]
brew install Macaulay2/tap/M2 
ran, but in /usr/local/bin the M2 files claim to be v 1.19

**Comment by mahrud** [comment]
Thanks! I think the instructions on the website are not correct for M1 systems.  Could you try starting M2 in a terminal with:
```
$(brew --prefix M2)/bin/M2
```
and then running the usual `setup()` and `setupEmacs()`? I think if you then close the terminal/emacs and start it again it should find the correct one.

**Comment by eisenbud** [comment]
Thanks for the quick reply, but it didn't quite work:

(brew --prefix M2)/bin/M2

-bash: syntax error near unexpected token `/bin/M2'


David
--
David Eisenbud
Professor of Mathematics
University of California Berkeley
www.msri.org/~de

**Comment by eisenbud** [comment]
However, I tried to be (a little) smarter:

brew --prefix M2

/opt/homebrew/opt/macaulay2

hippo-133:~ de1$ cd /opt/homebrew/opt/macaulay2

hippo-133:macaulay2 de1$ ./M2

-bash: ./M2: No such file or directory

hippo-133:macaulay2 de1$ ls

INSTALL_RECEIPT.json bin libexec

README lib share

hippo-133:macaulay2 de1$ cd bin/

hippo-133:bin de1$ ls

M2 M2-binary

hippo-133:bin de1$ ./M2
--
David Eisenbud
Professor of Mathematics
University of California Berkeley
www.msri.org/~de

**Comment by mahrud** [comment]
Was the M2 in that directory the correct version?

**Comment by eisenbud** [comment]
Yes!
thanks again
David
--
David Eisenbud
Professor of Mathematics
University of California Berkeley
www.msri.org/~de

**Comment by mahrud** [comment]
@DanGrayson could you update this paragraph on the website:
> You will now find the program M2 in the directory /usr/local/bin (if you've installed homebrew in /usr/local, as they recommend), and it can be run with the command /usr/local/bin/M2. You may need to use this long form once to evaluate setup(), in case the command M2 runs a previously installed version; the settings take effect the next time you log in. (If you don't want /usr/local/bin added to your PATH by setup, then run the alternative command $(brew --prefix M2)/bin/M2 instead. The result will be that something like /usr/local/opt/macaulay2/bin is added to your PATH.)

Into this:

You will now find the program M2 in the directory `` `brew --prefix M2`/bin/M2``. You may need to use this long form once to evaluate `setup()`, in case the command M2 runs a previously installed version; the settings take effect the next time you log in.
