### ISSUE TITLE
Cannot install Macaulay2 in new Mac

### ISSUE THREAD

**Issue by PedroMaciasMarques** [Macaulay2/homebrew-tap#175]
I have just bought a new mac (MacBook Air M2 13' 2022), and tried to install Macaulay2 using homebrew, as recommended in the M2 web page. My laptop came with Monterey OS, and since it was not working, I updated to Ventura, and tried to install macaulay again. Both times the error I see is the following:

"
currentString:1:1:(3):[2]: error: installPackage: 2 error(s) occurred running examples for package Macaulay2Doc
dmat lu qq PLU
FAILED: Macaulay2/packages/CMakeFiles/install-Macaulay2Doc usr-dist/arm64-Darwin-macOS-13.2.1/lib/Macaulay2/Macaulay2Doc/.installed /tmp/macaulay2-20230223-2764-1st4ucc/M2-release-1.21/M2/BUILD/build-brew/Macaulay2/packages/CMakeFiles/install-Macaulay2Doc /tmp/macaulay2-20230223-2764-1st4ucc/M2-release-1.21/M2/BUILD/build-brew/usr-dist/arm64-Darwin-macOS-13.2.1/lib/Macaulay2/Macaulay2Doc/.installed 
cd /tmp/macaulay2-20230223-2764-1st4ucc/M2-release-1.21/M2/BUILD/build-brew/Macaulay2/packages && /tmp/macaulay2-20230223-2764-1st4ucc/M2-release-1.21/M2/BUILD/build-brew/usr-dist/arm64-Darwin-macOS-13.2.1/bin/M2 -q --stop --silent --no-preload --no-threads -e errorDepth=3 -e debugLevel=0 -e "installPackage(\"Macaulay2Doc\", Verbose => false, RerunExamples => false, CheckDocumentation => true, IgnoreExampleErrors => false, RemakeAllDocumentation => false, InstallPrefix => \"/tmp/macaulay2-20230223-2764-1st4ucc/M2-release-1.21/M2/BUILD/build-brew/usr-dist/\", UserMode => false, SeparateExec => true, DebuggingMode => true)" -e "\"info-\"|\"Macaulay2Doc\" << Macaulay2Doc#\"test number\" << close" -e "exit 0" && gzip -nf9 /tmp/macaulay2-20230223-2764-1st4ucc/M2-release-1.21/M2/BUILD/build-brew/usr-dist/common/share/info/Macaulay2Doc.info
ninja: build stopped: subcommand failed.
"

Is there an easy fix for this?

Thank you

**Comment by PedroMaciasMarques** [comment]
Dear Mahrud,

I have just tried your suggestion, it gave me the error message:

"Error: No available formula with the name "gcc"."

In any case, I tried to install Maculay2 again after that and the error was the same as above.

**Comment by mahrud** [comment]
That seems like a bigger problem. Could you tell me how exactly you tried to install Macaulay2?

**Comment by PedroMaciasMarques** [comment]
I followed the indications on Macaulay2 web page. I started by installing homebrew by running:

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

Then I tried to install Macaulay2, by running

brew install Macaulay2/tap/M2

This gave a lot of good messages. I have just repeated it and  I am copying and pasting the whole text in the terminal window:

"Last login: Fri Feb 24 09:15:05 on console
(base) pedromaciasmarques@Pedros-Air ~ % brew install Macaulay2/tap/M2
==> Downloading https://formulae.brew.sh/api/formula.json
######################################################################## 100.0%
==> Fetching macaulay2/tap/macaulay2
==> Downloading https://github.com/Macaulay2/M2/commit/c4bf16f3278118ff1b6fdf20d
Already downloaded: /Users/pedromaciasmarques/Library/Caches/Homebrew/downloads/ac963ad48c0661b05ac4a1f73dd8e6849b57769bffc050d958df262ef5ff1ed2--c4bf16f3278118ff1b6fdf20d4ad68441f4b26c5.patch
==> Downloading https://github.com/Macaulay2/M2/archive/refs/tags/release-1.21.t
Already downloaded: /Users/pedromaciasmarques/Library/Caches/Homebrew/downloads/b03ad43a23f645eabed8b116df2ac468d83d4aaa15520e71a73159c95c0c5156--M2-release-1.21.tar.gz
==> Installing macaulay2 from macaulay2/tap
==> Patching
==> Applying c4bf16f3278118ff1b6fdf20d4ad68441f4b26c5.patch
patching file 'M2/Macaulay2/packages/Normaliz.m2'
==> git clone https://github.com/Macaulay2/M2-emacs.git M2/Macaulay2/editors/ema
==> git clone https://github.com/Macaulay2/memtailor.git M2/submodules/memtailor
==> git clone https://github.com/Macaulay2/mathic.git M2/submodules/mathic
==> git clone https://github.com/Macaulay2/mathicgb.git M2/submodules/mathicgb
==> cmake -GNinja -SM2 -BM2/BUILD/build-brew -DBUILD_NATIVE=OFF -DCMAKE_PREFIX_P
==> cmake --build M2/BUILD/build-brew --target M2-core M2-emacs M2-highlightjs
==> cmake --build M2/BUILD/build-brew --target install-Macaulay2Doc
Last 15 lines from /Users/pedromaciasmarques/Library/Logs/Homebrew/macaulay2/07.cmake:
 -- capturing example results for "status"                                   -- 0.262402 seconds elapsed
 -- capturing example results for "Module _ List"                            -- 0.069027 seconds elapsed
 -- capturing example results for "sheaf(Variety)"                           -- 0.0677045 seconds elapsed
 -- capturing example results for "format"                                   -- 0.0685602 seconds elapsed
 -- capturing example results for "polynomial rings"                         -- 0.0745771 seconds elapsed
 -- making example results for "Grassmannian(ZZ,ZZ)"                         -- 0.451111 seconds elapsed
 -- capturing example results for "matrices to and from modules"             -- 0.070233 seconds elapsed
 -- capturing example results for "HH^ZZ SheafOfRings"                       -- 0.0693802 seconds elapsed
 -- capturing example results for "quotientRemainder"                        -- 0.0689415 seconds elapsed
 -- capturing example results for "ProjectiveHilbertPolynomial ZZ"           -- 0.0670718 seconds elapsed
currentString:1:1:(3):[2]: error: installPackage: 2 error(s) occurred running examples for package Macaulay2Doc
dmat lu qq PLU
FAILED: Macaulay2/packages/CMakeFiles/install-Macaulay2Doc usr-dist/arm64-Darwin-macOS-13.2.1/lib/Macaulay2/Macaulay2Doc/.installed /tmp/macaulay2-20230224-1220-28488t/M2-release-1.21/M2/BUILD/build-brew/Macaulay2/packages/CMakeFiles/install-Macaulay2Doc /tmp/macaulay2-20230224-1220-28488t/M2-release-1.21/M2/BUILD/build-brew/usr-dist/arm64-Darwin-macOS-13.2.1/lib/Macaulay2/Macaulay2Doc/.installed 
cd /tmp/macaulay2-20230224-1220-28488t/M2-release-1.21/M2/BUILD/build-brew/Macaulay2/packages && /tmp/macaulay2-20230224-1220-28488t/M2-release-1.21/M2/BUILD/build-brew/usr-dist/arm64-Darwin-macOS-13.2.1/bin/M2 -q --stop --silent --no-preload --no-threads -e errorDepth=3 -e debugLevel=0 -e "installPackage(\"Macaulay2Doc\", Verbose => false, RerunExamples => false, CheckDocumentation => true, IgnoreExampleErrors => false, RemakeAllDocumentation => false, InstallPrefix => \"/tmp/macaulay2-20230224-1220-28488t/M2-release-1.21/M2/BUILD/build-brew/usr-dist/\", UserMode => false, SeparateExec => true, DebuggingMode => true)" -e "\"info-\"|\"Macaulay2Doc\" << Macaulay2Doc#\"test number\" << close" -e "exit 0" && gzip -nf9 /tmp/macaulay2-20230224-1220-28488t/M2-release-1.21/M2/BUILD/build-brew/usr-dist/common/share/info/Macaulay2Doc.info
ninja: build stopped: subcommand failed.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/macaulay2/homebrew-tap/issues

These open issues may also help:
Cannot install Macaulay2 in new Mac https://github.com/Macaulay2/homebrew-tap/issues/175
The Homebrew tap Macaulay2/tap/fflas-ffpack prevents Sage from building https://github.com/Macaulay2/homebrew-tap/issues/68
(base) pedromaciasmarques@Pedros-Air ~ % 
"

**Comment by mahrud** [comment]
I don't understand how you got the previous output from running this command:
```
brew test gfan
```
Could you provide the full output for that?

**Comment by PedroMaciasMarques** [comment]
I have opened a terminal session, and ran the command at the start of the session, then I ran 

> brew install Macaulay2/tap/M2

and I ran the command again. Here is the whole result:

"Last login: Sun Feb 26 08:52:57 on console
(base) pedromaciasmarques@Pedros-Air ~ % brew test gfan
Error: No available formula with the name "gcc".
(base) pedromaciasmarques@Pedros-Air ~ % brew test gfan
Error: No available formula with the name "gcc".
(base) pedromaciasmarques@Pedros-Air ~ % brew install Macaulay2/tap/M2      
Running `brew update --auto-update`...
==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations

==> Auto-updated Homebrew!
==> Updated Homebrew from 5d06f6b9a to 4.0.3 (a13556a1a).
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################## 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################## 100.0%
No changes to formulae.


The 4.0.0 release notes are available on the Homebrew Blog:
  https://brew.sh/blog/4.0.0
The 4.0.3 changelog can be found at:
  https://github.com/Homebrew/brew/releases/tag/4.0.3
==> Fetching macaulay2/tap/macaulay2
==> Downloading https://github.com/Macaulay2/M2/commit/c4bf16f3278118ff1b6fdf20d
Already downloaded: /Users/pedromaciasmarques/Library/Caches/Homebrew/downloads/ac963ad48c0661b05ac4a1f73dd8e6849b57769bffc050d958df262ef5ff1ed2--c4bf16f3278118ff1b6fdf20d4ad68441f4b26c5.patch
==> Downloading https://github.com/Macaulay2/M2/archive/refs/tags/release-1.21.t
Already downloaded: /Users/pedromaciasmarques/Library/Caches/Homebrew/downloads/b03ad43a23f645eabed8b116df2ac468d83d4aaa15520e71a73159c95c0c5156--M2-release-1.21.tar.gz
==> Installing macaulay2 from macaulay2/tap
==> Patching
==> Applying c4bf16f3278118ff1b6fdf20d4ad68441f4b26c5.patch
patching file 'M2/Macaulay2/packages/Normaliz.m2'
==> git clone https://github.com/Macaulay2/M2-emacs.git M2/Macaulay2/editors/ema
==> git clone https://github.com/Macaulay2/memtailor.git M2/submodules/memtailor
==> git clone https://github.com/Macaulay2/mathic.git M2/submodules/mathic
==> git clone https://github.com/Macaulay2/mathicgb.git M2/submodules/mathicgb
==> cmake -GNinja -SM2 -BM2/BUILD/build-brew -DBUILD_NATIVE=OFF -DCMAKE_PREFIX_P
==> cmake --build M2/BUILD/build-brew --target M2-core M2-emacs M2-highlightjs
==> cmake --build M2/BUILD/build-brew --target install-Macaulay2Doc
Last 15 lines from /Users/pedromaciasmarques/Library/Logs/Homebrew/macaulay2/07.cmake:
 -- capturing example results for "status"                                   -- 0.262884 seconds elapsed
 -- capturing example results for "Module _ List"                            -- 0.0712208 seconds elapsed
 -- capturing example results for "sheaf(Variety)"                           -- 0.0689098 seconds elapsed
 -- capturing example results for "format"                                   -- 0.07128 seconds elapsed
 -- capturing example results for "polynomial rings"                         -- 0.0729525 seconds elapsed
 -- making example results for "Grassmannian(ZZ,ZZ)"                         -- 0.448169 seconds elapsed
 -- capturing example results for "matrices to and from modules"             -- 0.0711715 seconds elapsed
 -- capturing example results for "HH^ZZ SheafOfRings"                       -- 0.0734104 seconds elapsed
 -- capturing example results for "quotientRemainder"                        -- 0.0739398 seconds elapsed
 -- capturing example results for "ProjectiveHilbertPolynomial ZZ"           -- 0.0693164 seconds elapsed
currentString:1:1:(3):[2]: error: installPackage: 2 error(s) occurred running examples for package Macaulay2Doc
dmat lu qq PLU
FAILED: Macaulay2/packages/CMakeFiles/install-Macaulay2Doc usr-dist/arm64-Darwin-macOS-13.2.1/lib/Macaulay2/Macaulay2Doc/.installed /tmp/macaulay2-20230226-3732-11gyie2/M2-release-1.21/M2/BUILD/build-brew/Macaulay2/packages/CMakeFiles/install-Macaulay2Doc /tmp/macaulay2-20230226-3732-11gyie2/M2-release-1.21/M2/BUILD/build-brew/usr-dist/arm64-Darwin-macOS-13.2.1/lib/Macaulay2/Macaulay2Doc/.installed 
cd /tmp/macaulay2-20230226-3732-11gyie2/M2-release-1.21/M2/BUILD/build-brew/Macaulay2/packages && /tmp/macaulay2-20230226-3732-11gyie2/M2-release-1.21/M2/BUILD/build-brew/usr-dist/arm64-Darwin-macOS-13.2.1/bin/M2 -q --stop --silent --no-preload --no-threads -e errorDepth=3 -e debugLevel=0 -e "installPackage(\"Macaulay2Doc\", Verbose => false, RerunExamples => false, CheckDocumentation => true, IgnoreExampleErrors => false, RemakeAllDocumentation => false, InstallPrefix => \"/tmp/macaulay2-20230226-3732-11gyie2/M2-release-1.21/M2/BUILD/build-brew/usr-dist/\", UserMode => false, SeparateExec => true, DebuggingMode => true)" -e "\"info-\"|\"Macaulay2Doc\" << Macaulay2Doc#\"test number\" << close" -e "exit 0" && gzip -nf9 /tmp/macaulay2-20230226-3732-11gyie2/M2-release-1.21/M2/BUILD/build-brew/usr-dist/common/share/info/Macaulay2Doc.info
ninja: build stopped: subcommand failed.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/macaulay2/homebrew-tap/issues

These open issues may also help:
Cannot install Macaulay2 in new Mac https://github.com/Macaulay2/homebrew-tap/issues/175
The Homebrew tap Macaulay2/tap/fflas-ffpack prevents Sage from building https://github.com/Macaulay2/homebrew-tap/issues/68
(base) pedromaciasmarques@Pedros-Air ~ % brew test gfan               
Fetching gem metadata from https://rubygems.org/.......
Using concurrent-ruby 1.2.0
Using minitest 5.17.0
Using bindata 2.4.15
Using zeitwerk 2.6.7
Using bundler 2.3.26
Using public_suffix 5.0.1
Using ast 2.4.2
Using connection_pool 2.3.0
Using msgpack 1.6.0
Using diff-lcs 1.5.0
Using byebug 11.1.3
Using did_you_mean 1.6.3
Using regexp_parser 2.7.0
Using docile 1.4.0
Using hpricot 0.8.6
Using json 2.6.3
Using uri_template 0.7.0
Using unf_ext 0.0.8.2
Using net-http-digest_auth 1.4.1
Using racc 1.6.2
Using rubyntlm 0.6.3
Using hana 1.3.7
Using webrobots 0.1.2
Fetching mime-types-data 3.2023.0218.1
Using webrick 1.8.1
Using mustache 1.1.1
Using rack 3.0.4.1
Using rainbow 3.1.1
Using parallel 1.22.1
Using rdiscount 2.2.7
Using rspec-support 3.12.0
Fetching plist 3.7.0
Using sorbet-runtime 0.5.10461
Using rexml 3.2.5
Using ruby-progressbar 1.11.0
Using unicode-display_width 2.4.2
Using ruby-macho 3.0.0
Using simplecov_json_formatter 0.1.4
Using simplecov-html 0.12.3
Using warning 1.3.0
Using i18n 1.12.0
Using tzinfo 2.0.6
Using elftools 1.2.0
Using bootsnap 1.16.0
Using net-http-persistent 4.0.1
Using parser 3.2.1.0
Using ecma-re-validator 0.4.0
Using addressable 2.8.1
Using unf 0.1.4
Using nokogiri 1.13.10 (arm64-darwin)
Using parallel_tests 3.13.0
Using ronn 0.7.3
Using rspec-core 3.12.1
Using rspec-expectations 3.12.2
Using rspec-mocks 3.12.3
Using rspec-sorbet 1.9.1
Using simplecov 0.22.0
Using activesupport 6.1.7.2
Using patchelf 1.4.0
Using json_schemer 0.2.24
Using rubocop-ast 1.26.0
Using domain_name 0.5.20190701
Using rspec-github 2.4.0
Using rspec-retry 0.6.2
Using rspec-its 1.3.0
Using rspec_junit_formatter 0.6.0
Using rspec 3.12.0
Using simplecov-cobertura 2.1.0
Using http-cookie 1.0.5
Fetching rubocop 1.46.0
Installing plist 3.7.0
Installing mime-types-data 3.2023.0218.1
Installing rubocop 1.46.0
Using mime-types 3.4.1
Using mechanize 2.8.5
Using rubocop-capybara 2.17.1
Using rubocop-performance 1.16.0
Using rubocop-rails 2.17.4
Using rubocop-sorbet 0.7.0
Using rubocop-rspec 2.18.1
Bundle complete! 34 Gemfile dependencies, 77 gems now installed.
Bundled gems are installed into `../../opt/homebrew/Library/Homebrew/vendor/bundle`
Removing plist (3.6.0)
Removing rubocop (1.45.1)
Removing mime-types-data (3.2022.0105)
Error: No available formula with the name "gcc".
(base) pedromaciasmarques@Pedros-Air ~ % 
"

**Comment by mahrud** [comment]
You don't need to rerun `brew install Macaulay2/tap/M2` after every command.

Could you run
```
brew config
brew doctor
```
and paste the results? (no need to install M2 again)

**Comment by PedroMaciasMarques** [comment]
Ok, here it is:

"Last login: Sun Feb 26 15:25:20 on ttys000
(base) pedromaciasmarques@Pedros-Air ~ % brew config
HOMEBREW_VERSION: 4.0.3-154-ga13556a
ORIGIN: https://github.com/Homebrew/brew
HEAD: a13556a1a60b527fa96c2dd5ecaf9b185f1f4da8
Last commit: 4 hours ago
Core tap JSON: 26 Feb 15:55 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
(base) pedromaciasmarques@Pedros-Air ~ % brew doctor
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################## 100.0%
Your system is ready to brew.
(base) pedromaciasmarques@Pedros-Air ~ % 
"

**Comment by mahrud** [comment]
Could you try
```
brew install gcc
```
and then again
```
brew test gfan
```
Alternatively, try:
```
brew remove gfan
brew install --build-bottle gfan
```

**Comment by PedroMaciasMarques** [comment]
Problem solved. By running the first two commands, there were no errors and I could install Maculay2 after that. 

Thank you very much!!!
