### ISSUE TITLE
new 1.22 install can't find flint

### ISSUE THREAD

**Issue by denham0** [Macaulay2/homebrew-tap#196]
I've been trying to update to version 1.22 on OS X (13.6.1) but once I think I'm done, M2 crashes with the following error:

`brew --prefix M2`/bin/M2
dyld[5223]: Library not loaded: /usr/local/opt/flint/lib/libflint-17.dylib
 Referenced from: <238BE5E0-D968-3476-8D0E-FE68D564740F> /usr/local/Cellar/macaulay2/1.22_1/bin/M2-binary 
(etc.)

[denham:~]$ brew install flint
Warning: flint 3.0.0 is already installed and up-to-date.

I'm a homebrew novice, so all I could think of doing was to remove the packages, reinstall, try again, and get the same results.  Thanks in advance for any suggestions.

**Comment by denham0** [comment]
If it helps, flint passes its own tests:

brew test flint
==> Testing flint
==> /usr/bin/clang test.c -I/usr/local/Cellar/flint/3.0.0/include/flint -L/usr/local/Cellar
==> ./test 2

I also checked gfan, since that was broken for me in 1.21 as well:

brew test gfan
==> Testing macaulay2/tap/gfan
gcc-11: warning: could not understand version 13.05.00
==> /usr/local/Cellar/gfan/0.6.2_10/bin/gfan _version
Last 15 lines from /Users/denham/Library/Logs/Homebrew/gfan/test.01.gfan:
2023-11-03 13:02:38 +0100

/usr/local/Cellar/gfan/0.6.2_10/bin/gfan
_version

dyld[9028]: Library not loaded: /usr/local/opt/gcc/lib/gcc/current/libgcc_s.1.1.dylib
  Referenced from: <4447C442-F01A-3011-8113-0903BECA72E8> /usr/local/Cellar/gfan/0.6.2_10/bin/gfan
  Reason: tried: '/usr/local/opt/gcc/lib/gcc/current/libgcc_s.1.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/gcc/lib/gcc/current/libgcc_s.1.1.dylib' (no such file), '/usr/local/opt/gcc/lib/gcc/current/libgcc_s.1.1.dylib' (no such file), '/usr/local/lib/libgcc_s.1.1.dylib' (no such file), '/usr/lib/libgcc_s.1.1.dylib' (no such file, not in dyld cache)
Error: macaulay2/tap/gfan: failed
Warning: Removed Sorbet lines from backtrace!
Rerun with --verbose to see the original backtrace
An exception occurred within a child process:
  BuildError: Failed executing: /usr/local/Cellar/gfan/0.6.2_10/bin/gfan _version
/usr/local/homebrew/Library/Homebrew/formula.rb:2737:in `block in system'
/usr/local/homebrew/Library/Homebrew/formula.rb:2673:in `open'
/usr/local/homebrew/Library/Homebrew/formula.rb:2673:in `system'
/usr/local/homebrew/Library/Taps/macaulay2/homebrew-tap/Formula/gfan.rb:48:in `block in <class:Gfan>'
/usr/local/homebrew/Library/Homebrew/formula.rb:2496:in `block (3 levels) in run_test'
/usr/local/homebrew/Library/Homebrew/extend/kernel.rb:499:in `with_env'
/usr/local/homebrew/Library/Homebrew/formula.rb:2495:in `block (2 levels) in run_test'
/usr/local/homebrew/Library/Homebrew/formula.rb:1052:in `with_logging'
/usr/local/homebrew/Library/Homebrew/formula.rb:2494:in `block in run_test'
/usr/local/homebrew/Library/Homebrew/mktemp.rb:75:in `block in run'
/usr/local/homebrew/Library/Homebrew/mktemp.rb:75:in `chdir'
/usr/local/homebrew/Library/Homebrew/mktemp.rb:75:in `run'
/usr/local/homebrew/Library/Homebrew/formula.rb:2788:in `mktemp'
/usr/local/homebrew/Library/Homebrew/formula.rb:2488:in `run_test'
/usr/local/homebrew/Library/Homebrew/test.rb:44:in `block in <main>'
/usr/local/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/usr/local/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/usr/local/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/usr/local/homebrew/Library/Homebrew/test.rb:48:in `<main>'

**Comment by mahrud** [comment]
Thank for the report. Give it another try now.

**Comment by denham0** [comment]
Thanks, Mahrud.  It's good now.  And gfan works too, which was really what prompted me to do the update in the first place.
