### ISSUE TITLE
SHA mismatch

### ISSUE THREAD

**Issue by LukeOeding** [Macaulay2/homebrew-tap#199]
Hi All,
I'm getting an SHA256 mismatch, and I've tried the standard things recommended when googling (like brew update, brew clean, brew uninstall Macaulay2, install Macaulay2, physically delete this file and do all of the above again), but nothing seems to fix this issue. Any ideas? This is for a 10 year old Mac running 11.7.10. 
```
Error: macaulay2: SHA256 mismatch
Expected: accf5eeddde623d179c8fee9d15cfb7d66d7a90cc7684d11c96ad9b3f3655dbb
  Actual: 159d2156810a6bb240410cd61eb641add85088d9f15c888cdaa37b8681f929ce
    File: /Users/lukeadmin/Library/Caches/Homebrew/downloads/72bc89d96bdbf4288b629083ea26198d96348adc6b77eb7cd9f2ab0806fcffa6--nauty2_8_8.tar.gz
To retry an incomplete download, remove the file above.```

**Comment by mahrud** [comment]
The error you're getting is from the formula for `nauty`, which is actually provided by the official Homebrew tap, not this one, and I noticed that they don't have a bottle for macOS 11 (Big Sur) anymore. It's possible that your macOS is too old. Brew's documentation says macOS 11 and older are "unsupported but may work" ([ref](https://docs.brew.sh/Installation#2)).

What do `brew config` and `brew doctor` say? You might be able to build `nauty` yourself with `brew install -s nauty` and then build M2, but I would try upgrading to macOS 12 instead.

**Comment by mahrud** [comment]
I'll close this for now. Feel free to reopen if upgrading to macOS 12 doesn't help.
