### ISSUE TITLE
M2 does not install on  macOS 14.2.1 Sonoma

### ISSUE THREAD

**Issue by WolfgL** [Macaulay2/homebrew-tap#203]
HI, I got this error when trying to install M2 via home-brew.
OS: macOS 14.2.1 Sonoma
--
...
0.054617 seconds elapsed
 -- capturing example results for "quotientRemainder"                        -- 0.0544502 seconds elapsed
 -- capturing example results for "ProjectiveHilbertPolynomial ZZ"           -- 0.0527198 seconds elapsed
currentString:1:1:(3):[2]: error: installPackage: 14 error(s) occurred running examples for package Macaulay2Doc
dmat lu qq PLU
FAILED: Macaulay2/packages/CMakeFiles/install-Macaulay2Doc usr-dist/arm64-Darwin-macOS-14.2.1/lib/Macaulay2/Macaulay2Doc/.installed /tmp/macaulay2-20231230-2566-wwgisx/M2-release-1.22/M2/BUILD/build-brew/Macaulay2/packages/CMakeFiles/install-Macaulay2Doc /tmp/macaulay2-20231230-2566-wwgisx/M2-release-1.22/M2/BUILD/build-brew/usr-dist/arm64-Darwin-macOS-14.2.1/lib/Macaulay2/Macaulay2Doc/.installed 
cd /tmp/macaulay2-20231230-2566-wwgisx/M2-release-1.22/M2/BUILD/build-brew/Macaulay2/packages && /tmp/macaulay2-20231230-2566-wwgisx/M2-release-1.22/M2/BUILD/build-brew/usr-dist/arm64-Darwin-macOS-14.2.1/bin/M2 -q --stop --silent --no-preload --no-threads -e errorDepth=3 -e debugLevel=0 -e "installPackage(\"Macaulay2Doc\", Verbose => false, RerunExamples => false, CheckDocumentation => true, IgnoreExampleErrors => false, RemakeAllDocumentation => false, InstallPrefix => \"/tmp/macaulay2-20231230-2566-wwgisx/M2-release-1.22/M2/BUILD/build-brew/usr-dist/\", UserMode => false, SeparateExec => true, DebuggingMode => true)" -e "\"info-\"|\"Macaulay2Doc\" << Macaulay2Doc#\"test number\" << close" -e "exit 0" && gzip -nf9 /tmp/macaulay2-20231230-2566-wwgisx/M2-release-1.22/M2/BUILD/build-brew/usr-dist/common/share/info/Macaulay2Doc.info
ninja: build stopped: subcommand failed.

What is going wrong? Wolfgang

**Comment by mahrud** [comment]
See the discussion in #202. Feel free to comment there if the workaround provided doesn't resolve the problem.
