### ISSUE TITLE
Home brew and macOS 14.2.1

### ISSUE THREAD

**Issue by n-m-g** [Macaulay2/homebrew-tap#205]
Hi,

More recently, I updated my operating system to macOS Sonoma 14.2.1 and when I tried to install the current release of M2 using the command:

brew install Macaulay2/tap/M2

I encountered an error message.

A portion of the terminal session is:

--
--
==> Installing macaulay2/tap/macaulay2
==> Patching
==> Applying 84c7b9f67bfdb6b821e24546ab2dd4e2455dfdbf.patch
patching file 'M2/Macaulay2/e/aring-gf-flint-big.hpp'
patching file 'M2/Macaulay2/e/aring-gf-flint.hpp'
patching file 'M2/Macaulay2/e/aring-qq-flint.hpp'
patching file 'M2/Macaulay2/e/aring-zz-flint.hpp'
patching file 'M2/Macaulay2/e/aring-zzp-flint.hpp'
patching file 'M2/Macaulay2/e/dmat-gf-flint-big.hpp'
patching file 'M2/Macaulay2/e/dmat-gf-flint.hpp'
patching file 'M2/Macaulay2/e/dmat-lu-inplace.hpp'
patching file 'M2/Macaulay2/e/dmat-lu-zzp-flint.hpp'
patching file 'M2/Macaulay2/e/dmat-qq-flint.hpp'
patching file 'M2/Macaulay2/e/dmat-zz-flint.hpp'
patching file 'M2/Macaulay2/e/dmat-zzp-flint.hpp'
patching file 'M2/Macaulay2/e/interface/flint.cpp'
patching file 'M2/Macaulay2/e/interface/ring.cpp'
patching file 'M2/Macaulay2/e/mat-linalg.hpp'
==> git clone https://github.com/Macaulay2/M2-emacs.git M2/Macaulay2/editors/ema
==> git clone https://github.com/Macaulay2/memtailor.git M2/submodules/memtailor
==> git clone https://github.com/Macaulay2/mathic.git M2/submodules/mathic
==> git clone https://github.com/Macaulay2/mathicgb.git M2/submodules/mathicgb
==> cmake -GNinja -SM2 -BM2/BUILD/build-brew -DBUILD_NATIVE=OFF -DCMAKE_PREFIX_P
==> cmake --build M2/BUILD/build-brew --target M2-core M2-emacs M2-highlightjs
==> cmake --build M2/BUILD/build-brew --target install-Macaulay2Doc
Last 15 lines from /Users/nathangrieve/Library/Logs/Homebrew/macaulay2/07.cmake:
 -- capturing example results for "Module _ List"                            -- 0.0623203 seconds elapsed
 -- capturing example results for "sheaf(Variety)"                           -- 0.0605192 seconds elapsed
 -- capturing example results for "format"                                   -- 0.0600026 seconds elapsed
 -- capturing example results for "polynomial rings"                         -- 0.0656161 seconds elapsed
 -- making example results for "Grassmannian(ZZ,ZZ)"                         -- 0.463332 seconds elapsed
 -- capturing example results for "matrices to and from modules"             -- 0.0631704 seconds elapsed
 -- capturing example results for "HH^ZZ SheafOfRings"                       -- 0.0618523 seconds elapsed
 -- capturing example results for "quotientRemainder"                        -- 0.0617456 seconds elapsed
 -- capturing example results for "ProjectiveHilbertPolynomial ZZ"           -- 0.0601177 seconds elapsed
currentString:1:1:(3):[2]: error: installPackage: 14 error(s) occurred running examples for package Macaulay2Doc
dmat lu qq PLU
FAILED: Macaulay2/packages/CMakeFiles/install-Macaulay2Doc usr-dist/arm64-Darwin-macOS-14.2.1/lib/Macaulay2/Macaulay2Doc/.installed /tmp/macaulay2-20240115-57938-3y8iht/M2-release-1.22/M2/BUILD/build-brew/Macaulay2/packages/CMakeFiles/install-Macaulay2Doc /tmp/macaulay2-20240115-57938-3y8iht/M2-release-1.22/M2/BUILD/build-brew/usr-dist/arm64-Darwin-macOS-14.2.1/lib/Macaulay2/Macaulay2Doc/.installed 
cd /tmp/macaulay2-20240115-57938-3y8iht/M2-release-1.22/M2/BUILD/build-brew/Macaulay2/packages && /tmp/macaulay2-20240115-57938-3y8iht/M2-release-1.22/M2/BUILD/build-brew/usr-dist/arm64-Darwin-macOS-14.2.1/bin/M2 -q --stop --silent --no-preload --no-threads -e errorDepth=3 -e debugLevel=0 -e "installPackage(\"Macaulay2Doc\", Verbose => false, RerunExamples => false, CheckDocumentation => true, IgnoreExampleErrors => false, RemakeAllDocumentation => false, InstallPrefix => \"/tmp/macaulay2-20240115-57938-3y8iht/M2-release-1.22/M2/BUILD/build-brew/usr-dist/\", UserMode => false, SeparateExec => true, DebuggingMode => true)" -e "\"info-\"|\"Macaulay2Doc\" << Macaulay2Doc#\"test number\" << close" -e "exit 0" && gzip -nf9 /tmp/macaulay2-20240115-57938-3y8iht/M2-release-1.22/M2/BUILD/build-brew/usr-dist/common/share/info/Macaulay2Doc.info
ninja: build stopped: subcommand failed.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/macaulay2/homebrew-tap/issues

--
--

Have others encountered similar issues?  Many thanks.

**Comment by mahrud** [comment]
See the discussion in https://github.com/Macaulay2/homebrew-tap/issues/202. Feel free to comment there if the workaround provided doesn't resolve the problem.
