### ISSUE TITLE
Error when calling Macaulay2 package

### ISSUE THREAD

**Issue by raluvlad10** [Macaulay2/homebrew-tap#210]
I started encountering an error when attempting to call packages in Macaulay2. It used to work fine. However, since the last time it worked, I have updated my computer software. (I am currently using an M1 Mac, with macOS Sonoma 14.3.1.)

I reached out to the IT group at my local institution. A technician there said that he tried to install Homebrew and Macaulay2 on an otherwise empty Mac, and got the same error message. So he believes it's possible that this is an error of Macaulay2 with the newest macOS.

It looks like normaliz is installed in a directory that's not on my PATH. In particular, when attempting to call a package in Macaulay2, I get the following message:

error: could not find normaliz
 
Moreover, the command 

/opt/homebrew/bin/normaliz --help

also gives an error message. See attached. 

[Macaulay2-error.pdf](https://github.com/Macaulay2/M2/files/14458212/Macaulay2-error.pdf)

**Comment by mahrud** [comment]
Try reinstalling normaliz:
```
brew remove --ignore-dependencies normaliz
brew install --build-bottle normaliz
```

**Comment by raluvlad10** [comment]
Hi,

I ran the commands, and got the following error message.

**Comment by mahrud** [comment]
You didn't provide an error message. I just uploaded a new version of normaliz and M2, try `brew upgrade` and let me know if this happens again.

**Comment by raluvlad10** [comment]
It works now, thanks!
