### ISSUE TITLE
The Homebrew tap Macaulay2/tap/fflas-ffpack prevents Sage from building

### ISSUE THREAD

**Issue by slel** [Macaulay2/homebrew-tap#68]
Reported on sage-release:

- https://groups.google.com/g/sage-release/c/hVIsURxpdhc/m/pHEUOJF_BAAJ
- https://groups.google.com/g/sage-release/c/hVIsURxpdhc/m/U9SssCc2CgAJ

**Comment by mahrud** [comment]
Is this still a problem? This [message](https://groups.google.com/g/sage-release/c/hVIsURxpdhc/m/oo4d0ODvAQAJ) on the groups seems to indicate that another problem was involved, but I didn't read the thread too carefully so could be different issues.

**Comment by slel** [comment]
Back in February I uninstalled M2 to get Sage to build.
Hoping to try again when I find time.

**Comment by slel** [comment]
Someone seems to have bumped into this again:

- https://groups.google.com/g/sage-devel/c/r-CkHRoyDZk

**Comment by slel** [comment]
Trying to give this another go and getting stuck elsewhere:
one can now `brew install singular`, so `factory` conflicts.

**Comment by mahrud** [comment]
> Trying to give this another go and getting stuck elsewhere: one can now `brew install singular`, so `factory` conflicts.

If I remember the warnings correctly, you can safely disregard them. If that's not the case, could you make an issue with the errors?

**Comment by slel** [comment]
Another report on interference between M2 taps and building Sage:

- https://groups.google.com/g/sage-devel/c/ox0vdgfK52s

**Comment by mahrud** [comment]
> Another report on interference between M2 taps and building Sage:
> 
> - https://groups.google.com/g/sage-devel/c/ox0vdgfK52s

This seems to be a problem with Sage not working with recent versions of givaro/fflas_ffpack, no?

I'm still not sure what change you'd like to be made here.

**Comment by mahrud** [comment]
I'll close this for now, because the warning printed by brew when any other problem occurs keeps confusing people and making them thing it's related to this issue. However, if anything changes on Sage's side with regards to OpenMP or you think of a solution feel free to reopen or let me know.
