### ISSUE TITLE
Issue installing M2 on Apple Silicon / Big Sur

### ISSUE THREAD

**Issue by mayestang** [Macaulay2/homebrew-tap#69]
Hello!

I've installed M2 many times over the years the "traditional way" but was excited to see that the Homebrew installation is now available.  Brew is able to install other programs, but I am running into problems with M2.   I'm on a MacBook Air M1 with Big Sur.

The terminal code is below - a helpful former student tells me that it's at the stage of installing dependences, when installing MP code.

I'm not really sure what is going on or how to fix it.  Any explanations would be very helpful. Thank you!

```
 Installing mpsolve from macaulay2/tap
==> Downloading https://raw.githubusercontent.com/Macaulay2/M2/35c3e5e5f03cb2e60baa8e69f8109afcdb5fdc7b/M2
Already downloaded: /Users/sarahmayes1/Library/Caches/Homebrew/downloads/39fe3b12ab6d0421c68eb9b55cea05b0c30a8adb7a2c1303ef1eb818b5cd929c--patch-3.2.1
==> Downloading https://numpi.dm.unipi.it/_media/software/mpsolve/mpsolve-3.2.1.tar.gz
Already downloaded: /Users/sarahmayes1/Library/Caches/Homebrew/downloads/f31f526adb593a1df8ba3f344e0fe3455ed1ea44de23b7b3d2c64fe68f871d77--mpsolve-3.2.1.tar.gz
==> Patching
==> Applying patch-3.2.1
patching file configure.ac
patching file src/mpsolve/Makefile.am
patching file configure.ac
==> autoreconf -vif
==> ./configure --disable-examples --disable-ui --disable-documentation GMP_CFLAGS=-I/opt/homebrew/opt/gmp
Last 15 lines from /Users/sarahmayes1/Library/Logs/Homebrew/mpsolve/02.configure:
checking for getline... yes
checking for strndup... yes
checking if C99 complex.h is supported from the C++ compiler... no
checking for pow in -lm... yes
checking for __gmpz_init2 in -lgmp... yes
checking for main in -lgmpxx... yes
checking for gmp.h... yes
checking for pkg-config... /opt/homebrew/Library/Homebrew/shims/mac/super/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for check >= 0.9.4... no
checking for gtk+-3.0... no
checking for gtk+-2.0... no
checking for cairo... no
./configure: line 24983: syntax error near unexpected token `newline'
./configure: line 24983: `    '''

Do not report this issue to Homebrew/brew or Homebrew/core!
```

**Comment by mahrud** [comment]
Thanks for making the report!

Your student is right; the error is in building the `mpsolve` bottle which Macaulay2 uses for polynomial solving.

Unfortunately I don't have access to an M1 system. Could you try running:
```
brew install --keep-tmp macaulay2/tap/mpsolve
```
then you should see something like:
```
==> Temporary files retained at:
/tmp/mpsolve-20210405-1713594-ts8jcm
```
and upload the files `configure` and `config.log` from inside the temporary directory.

@tom111 have you had an issue like this?

**Comment by mayestang** [comment]
Thanks @mahrud! I appreciate the clear instructions.  Here is the `config.log` file. 

Could you clarify what configure file you'd like to see?  There's a configure.ac and a configure terminal file that I cannot upload here.


[config.log](https://github.com/Macaulay2/homebrew-tap/files/6266269/config.log)

**Comment by mahrud** [comment]
I meant the `configure` script. You can upload it on gist.github.com instead or rename the file to add a .txt extension.

**Comment by tom111** [comment]
> @tom111 have you had an issue like this?

I can't remember any issues like that. Unfortunately I won't be able to work on my M1 machine and test before the weekend.

**Comment by tom111** [comment]
I have mpsolve successfully installed, but I can reproduce the problem. Reinstall would not work now. The problem in that configure script is that it is the second to last line in this block:
```
if test ${ac_cv_path_MEX+y}
then :
  printf %s "(cached) " >&6
else $as_nop
  if test -z "$MEX"; then
  ac_path_MEX_found=false
  # Loop through the user's path and test for each of PROGNAME-LIST
  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
for as_dir in $PATH
do
  IFS=$as_save_IFS
  case $as_dir in #(((
    ''
fi
```
That seems to be two single quotes with nothing between them? I can send you the secret gist @mahrud. (Does posting a configure containing gist here leak any personal information about me or my computer?)

**Comment by mahrud** [comment]
The solution in https://github.com/robol/MPSolve/issues/27 seems to work. I'm building a new bottle now.

**Comment by mahrud** [comment]
@mayestang by the way, were you able to build the new version of Macaulay2 after the fix? Feel free to reopen the issue if it persists.
