### ISSUE TITLE
First time brew install on MacOS BigSur: dyld library not loading

### ISSUE THREAD

**Issue by Sondzus** [Macaulay2/homebrew-tap#96]
My first time trying to install M2 using brew. 

* installed homebrew. 
* ran `  brew install Macaulay2/tap/M2`

No obvious errors reports (I think). 

Then I try `/usr/local/bin/M2` and get this:
 ```
$ /usr/local/bin/M2
dyld: Library not loaded: /usr/local/opt/ntl/lib/libntl.43.dylib
  Referenced from: /usr/local/bin/M2-binary
  Reason: image not found
/usr/local/bin/M2: line 2: 69331 Abort trap: 6           DYLD_LIBRARY_PATH=`dirname "$0"`/../lib/Macaulay2/lib:$DYLD_LIBRARY_PATH `dirname "$0"`/M2-binary "$@"
```

I have no idea what to do next.

**Comment by mahrud** [comment]
This will be fixed with #94, but in the meantime do:
```
brew switch ntl 11.5.0
```

**Comment by Sondzus** [comment]
Oh, thanks @mahrud  (this doesn't work, so I can wait).

**Comment by mahrud** [comment]
Try `brew update` now.

**Comment by mahrud** [comment]
Ah, looks like the flint bottle was updated. I'll update the M2 bottle as well. Try again sometime tonight, it should be fixed by then.

**Comment by mahrud** [comment]
Should be fixed now. Let me know if you still run into errors.

**Comment by LukeOeding** [comment]
It works now (even if it says "Big Sur" in the bottle name.  Thank you!
